"""baseline: entry spine + journal + idea

Revision ID: b60c2afb9e7b
Revises: 
Create Date: 2026-06-15 00:07:13.599338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60c2afb9e7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('journal', 'idea', name='entrytype'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'csv', 'xlsx', 'derived', name='sourcetype'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_type'), ['type'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('entry_tags',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    op.create_table('idea_details',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'reviewing', 'pursuing', 'archived', name='ideastatus'), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    with op.batch_alter_table('idea_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_details_status'), ['status'], unique=False)

    op.create_table('journal_details',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_details')
    with op.batch_alter_table('idea_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_details_status'))

    op.drop_table('idea_details')
    op.drop_table('entry_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_type'))
        batch_op.drop_index(batch_op.f('ix_entries_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_entries_category'))

    op.drop_table('entries')
    # ### end Alembic commands ###
